# Generated by Django 6.0.6 on 2026-06-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('account_type', models.CharField(choices=[('bank', 'Bank'), ('card', 'Credit Card')], max_length=10)),
                ('ownership', models.CharField(choices=[('private', 'Private'), ('joint', 'Joint')], max_length=10)),
                ('folder_path', models.CharField(blank=True, max_length=500)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['account_type', 'name'],
            },
        ),
    ]
