# Generated by Django 5.2.15 on 2026-07-07 05:36

from django.db import migrations


def seed_accounts(apps, schema_editor):
    Account = apps.get_model('accounts', 'Account')
    accounts = [
        {'name': 'Mizrachi',      'account_type': 'bank', 'ownership': 'joint'},
        {'name': 'Bank Leumi',    'account_type': 'bank', 'ownership': 'private'},
        {'name': 'Bank Hapoalim', 'account_type': 'bank', 'ownership': 'private'},
        {'name': 'Max Uniq',      'account_type': 'card', 'ownership': 'joint'},
        {'name': 'Visa Cal 4779', 'account_type': 'card', 'ownership': 'private'},
        {'name': 'Visa Cal 7353', 'account_type': 'card', 'ownership': 'private'},
        {'name': 'Isracard',      'account_type': 'card', 'ownership': 'joint'},
    ]
    for data in accounts:
        Account.objects.create(**data)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_accounts, migrations.RunPython.noop),
    ]
