# Generated by Django 6.0.6 on 2026-09-05 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_seed_initial_accounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file_hash', models.CharField(max_length=64)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_reviews', to='accounts.account')),
            ],
            options={
                'unique_together': {('account', 'filename')},
            },
        ),
    ]
